export default {
  HOME: '/',
  LOGIN: '/login',
  SALARY: '/salary',
  GENERAL: '/general',
  PUBLICDETAIL: '/public-detail',
  OVERTIME: '/overtime',
  SALARYOFMONTH13: '/salary-of-month-13',
  TOTALLEAVE: '/total-leave',
  SALARYPROCESS: '/salary-process',
  ORTHERMONEY: '/orther-money',
  SALARYADVANCE: '/salary-advance',
  CREATEREQUEST: '/create-request',
  DEPARMENT: '/deparment',
  POSITION: '/position',
};
