export default {
  HOME: '/',
  LOGIN: '/login',
  LEAVE: '/leave',
  SHIFT: '/shift',
  TIME: '/time',
  EMPLOYEE: '/employee',
  REPORT: '/report',
  ACCOUNT: '/account',
  SALARY: '/salary',
  SYN: '/syn',
  DATA: '/data',
  DETAIL: '/detail',
  GENERAL: '/general',
  TIMESHEETDATA: '/timesheetdata',
  LATEEARLY: '/late-in-early-out',
  REGISTEROVERTIME: '/reagister-overtime',
};
